################################################# _ ###################
#注意事项
#
# - 环境变量的格式为“键=值”，顶格写，或者每个号不能有空格，值可以用单引号引起来，不要引也行（下面的特殊情况必须引起来）
# - 因为环境中的变量“#”代表注释，如果密码中存在“#”字符的，一定要使用单引号将整个密码引起#来，否则单会在“#”结束前，如果密码中存在引号的，
#    需要在单双引号前加“\”转义
# - 配置多账户不可省略单引号，且多个和密码的格式必须是“<账1>@<密码1>|<账2>@<密码2>|<账3>@<密码3> ”，不要空格，让有程序给你干掉
#     eg MULTIPLE_ACCOUNTS='<账1>@<密码1>|<账2>@<密码2>|<账3>@<密码3>'
#    注意不要省略“<>”符号，否则不能正确匹配
# - 如果你只有和账户_，只配置FREENOMUSERNAME FREOM_PASSWORD 就够了
# -单账和多账的配置去会被合并收看并重
################################################# _ ###################

# .env 文件版本
ENV_FILE_VERSION= ' v2.3 '

# ###################账户配置###################### #
# Freenom 账户 Freenom 账户
FREENOM_USERNAME= ' '

# Freenom 密码 Freenom 密码
FREENOM_PASSWORD= ' '

#多账户支持支持多账户
MULTIPLE_ACCOUNTS= ' '

#【任选】 Freenom 代理 [可选] Freenom 代理 例如 http://127.0.0.1:1081 或 socks5://127.0.0.1:1080
FREENOM_PROXY= ' '
# ####################结束账簿配置########################配置

# #################### 通知邮件配置电子邮件配置###################### ##
#机器人账户邮箱 机器人邮箱
MAIL_USERNAME = '商口游@163.com '

#机器人邮箱密码（Gmail填写密码，QQ邮箱或163邮箱填写授权码） 机器人邮箱密码
邮件密码= ' '

#接收通知的邮箱 用于接收通知的邮箱地址
TO='859416872@qq.com ' _ _

#是否启用邮件功能：不启用 1：启用0：启用邮件推送功能 1：启用 0：未启用
MAIL_ENABLE=0

#【任选】自定义邮箱配置【可选】自定义邮箱配置
#如果你想使用这些除“QQ邮箱、163邮箱、Gmail、Outlook邮箱”以外的邮箱或者自建邮箱作为邮箱服务，可以自定义邮箱配置项，否则请不要配置
#如果想使用除“QQ邮箱、163邮箱、Gmail、Outlook邮箱”以外的邮箱或自建邮箱服务作为机器人邮箱，可以自定义邮箱配置，否则请不要配置这些项目。

#【任选】 SMTP 服务器 [可选] SMTP 服务器 例如 smtp.gmail.com
邮件主机= ' '

#【可选】 SMTP 端口号，一般为 587 或 465 [可选] SMTP 端口号，通常为 587 或 465
邮件端口= “ ”

#【任选】邮件加密方式，一般是 tls 或者 ssl 或者 starttls [可选] 邮件加密方式，通常是 tls 或者 ssl 或者 starttls
MAIL_ENCRYPTION= ' '

# end 自定义邮箱配置 end of custom email config

##################### end 通知邮件配置######################## #

# #################### 电报机器人########################
#通过 Telegram bot 发送通知消息 通过 Telegram bot 发送消息

#你的chat_id，通过发送“/start”给@userinfobot 可以获取自己的id 你的chat_id，你可以通过发送“/start”给@userinfobot来获取自己的id
TELEGRAM_CHAT_ID= ' '

#你的 Telegram bot 的 token 你的 Telegram bot 的令牌
TELEGRAM_BOT_TOKEN= ' '

#【任选】 Telegram 代理 [可选] Telegram 代理，例如 http://127.0.0.1:1081 或 socks5://127.0.0.1:1080
电报代理= ' '

#【任选】自建电报代理地址，不理解则请加载此配置项，默认保持【可选】请不要修改此项
#参考：https://web.archive.org/web/20220221035315/https://hostloc.com/thread-805441-1-1.html
#只要是一个智能主机，程序会自动提取网址的部分。例如 https://xxx.xx.workers.dev/ 或 xxx.xx.xx
CUSTOM_TELEGRAM_HOST= ' api.telegram.org '

#是否启用 Telegram Bot 功能 1：启用 0：未启用 是否启用 Telegram Bot 功能 1：启用 0：未启用
TELEGRAM_BOT_ENABLE=0
# ####################结束电报机器人#########################

######################企业微信#########################
#企业ID 企业ID
WECHAT_CORP_ID= ' '

#应用的凭证密钥 企业微信应用的凭证密钥
WECHAT_CORP_SECRET= ' '

#应用ID
WECHAT_AGENT_ID= ' '

#是否启用企业微信发送信功能 1：启用 0：不启用 是否启用企业微信消息推送功能 1：启用 0：不启用
微信启用=0
######################结束企业微信#########################

# ####################服务器酱########################
#服务器酱的 SendKey
SCT_SEND_KEY= ' '

#是否启用 Server 酱送信功能 1：启用 0：未启用 是否启用 ServerChan 消息功能 1：启用 0：未启用
SCT_ENABLE=0
# #################### 端服务器酱#########################

# ####################树皮送信#########################
# Bark key 打开Bark App，注册设备后查看的密钥 打开Bark App，注册设备，查看密钥
#直接支持粘贴“https://apiday.day.day.key应用程序直接成你自己的文字/内容”，关键应用程序直接支持“https://apiday.xxx.xxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.day.day.key应用程序” .app/xxx这里成你自己的文字内容/改成你自己的文字内容，“程序”类型的文字会自动提取有效的文字内容
BARK_KEY= ' '

# Bark域名默认服务是Bark作者提供的，建议自建Bark URL默认为Bark作者提供的服务器，建议自己搭建
BARK_URL= ' https: //api.day.app '

# Bark 相关其他参数（保持默认能够）
BARK_IS_ARCHIVE= ' '
BARK_GROUP = '免费名称'
BARK_LEVEL= '活跃'
BARK_ICON= ' https: //q2.qlogo.cn/headimg_dl?dst_uin=593198779&spec=100 '
BARK_JUMP_URL= ' '
BARK_SOUND= ' gotosleep '

#是否启用 Bark推送消息 0：不启用推送消息 1：是否启用 1：启用 0：不启用推送消息
BARK_ENABLE=0
##################### end Bark 送信#########################

#通知频率 0：只有当有续期操作的时候 1：每次执行 通知频率 0：只有更新操作 1：每次执行
NOTICE_FREQ=1

#是否验证服务器证书 1：验证 0：不验证 是否验证服务器证书 1：验证 0：不验证
验证_SSL=0

#是否开启 Debug 模式 1：开启 0：关闭 是否开启 Debug 模式 1：开启 0：关闭
调试=0

#检测是否有新版本，发现新版本时有推送消息通知： 1：开启有新版本，发现新版本时自动推送消息通知：开启 0：关闭
NEW_VERSION_DETECTION=1

#应用语言配置 应用语言配置，支持的值为zh或en，zh表示中文，en表示英文
语言=zh
